export const TEMPLATES = [
    {
        id: "universal-starter",
        name: "Universal Pro",
        category: "business",
        description: "Premium e-commerce store template with product catalog, collections, trust badges, FAQ, newsletter, testimonials, and full checkout-ready design.",
        content: {
            siteName: "LUXE",
            category: "business",
            theme: { primaryColor: "#1a1a2e", secondaryColor: "#6366f1", accentColor: "#f43f5e", backgroundColor: "#ffffff", textColor: "#0f172a", fontFamily: "Inter" },
            sections: [
                { id: "promo-1", type: "promo-banner", content: { texts: ["✨ Free Shipping on Orders Over $75 — Limited Time!", "🔥 New Arrivals Just Dropped — Shop the Latest Collection", "💎 Join LUXE Rewards — Earn Points on Every Purchase"], link: "#products", linkText: "Shop Now", backgroundColor: "" } },
                { id: "nav-1", type: "navbar", content: { logo: "LUXE", links: [{ label: "New In", href: "#collections" }, { label: "Shop All", href: "#products" }, { label: "Collections", href: "#collections" }, { label: "About", href: "#about" }, { label: "Help", href: "#faq" }], ctaText: "Cart (0)", ctaLink: "#cart" } },
                { id: "hero-1", type: "hero", content: { headline: "Curated Essentials for Modern Living", subheadline: "Discover our handpicked collection of premium lifestyle products — designed for those who appreciate quality, craftsmanship, and timeless style.", ctaText: "Shop New Arrivals", ctaLink: "#products", backgroundImage: "", overlayOpacity: 0.5 } },
                { id: "collect-1", type: "collection-grid", content: { title: "Shop by Category", subtitle: "Explore our curated collections designed for every style and occasion", collections: [{ name: "Premium Essentials", image: "", itemCount: "48 Products", href: "#" }, { name: "New Arrivals", image: "", itemCount: "24 Products", href: "#" }, { name: "Best Sellers", image: "", itemCount: "36 Products", href: "#" }, { name: "Limited Edition", image: "", itemCount: "12 Products", href: "#" }, { name: "Gift Sets", image: "", itemCount: "18 Products", href: "#" }, { name: "Sale", image: "", itemCount: "32 Products", href: "#" }] } },
                { id: "prod-1", type: "product-grid", content: { title: "Trending Now", subtitle: "Our most popular products hand-picked by our curation team", products: [{ name: "Minimal Leather Tote", price: "$189", image: "", description: "Hand-stitched Italian leather tote with brass hardware. Fits a 15\" laptop with dedicated pockets.", badge: "Bestseller" }, { name: "Ceramic Pour-Over Set", price: "$68", image: "", description: "Artisan-crafted ceramic dripper with thermal carafe. Makes 2-4 cups of perfectly extracted coffee.", badge: "New" }, { name: "Merino Wool Throw", price: "$145", image: "", description: "Ultra-soft 100% merino wool throw blanket. Ethically sourced from New Zealand. 60\" × 80\".", badge: "Popular" }, { name: "Soy Candle Collection", price: "$42", image: "", description: "Set of 3 hand-poured soy candles with essential oils. Cedar & Sage, Lavender, and Citrus Bloom.", badge: "" }, { name: "Linen Bed Set", price: "$249", image: "", description: "Stonewashed French linen duvet cover and pillowcases. Naturally breathable, softer with every wash.", badge: "Limited" }, { name: "Leather Card Wallet", price: "$58", image: "", description: "Slim full-grain leather wallet with RFID protection. Holds 6 cards and folded bills. Ages beautifully.", badge: "Gift Pick" }, { name: "Stoneware Mug Duo", price: "$36", image: "", description: "Set of 2 hand-thrown stoneware mugs with reactive glaze. Microwave and dishwasher safe. 12oz each.", badge: "" }, { name: "Organic Cotton Robe", price: "$95", image: "", description: "Heavyweight organic cotton terry robe with shawl collar and deep pockets. Available in 4 colors.", badge: "New" }] } },
                { id: "trust-1", type: "trust-badges", content: { badges: [{ icon: "🚚", title: "Free Shipping", description: "On orders over $75" }, { icon: "↩️", title: "Easy Returns", description: "30-day hassle-free returns" }, { icon: "🔒", title: "Secure Checkout", description: "256-bit SSL encryption" }, { icon: "💬", title: "24/7 Support", description: "Chat, email, or phone" }] } },
                { id: "feat-1", type: "features", content: { title: "Why Customers Love LUXE", subtitle: "We obsess over the details so you don't have to", items: [{ icon: "✨", title: "Curated Quality", description: "Every product is hand-selected by our team and tested for 30 days before it makes it to our store. We only carry items we'd use ourselves." }, { icon: "🌿", title: "Sustainably Made", description: "We partner with artisans and manufacturers who share our commitment to ethical production, fair wages, and environmental responsibility." }, { icon: "📦", title: "Premium Packaging", description: "Every order arrives beautifully packaged in recycled materials. Perfect for gifting — no additional wrapping needed." }, { icon: "💳", title: "Flexible Payments", description: "Pay in full or split into 4 interest-free installments with Shop Pay. We accept all major cards and digital wallets." }, { icon: "⭐", title: "Loyalty Rewards", description: "Earn 2x points on every purchase. Redeem for discounts, free shipping, or exclusive early access to new collections." }, { icon: "🎁", title: "Personal Styling", description: "Book a free 15-minute virtual styling session with our team. We'll help you find the perfect products for your space and lifestyle." }] } },
                { id: "testimonials-1", type: "testimonials", content: { title: "What Our Customers Say", subtitle: "Real reviews from real people — over 50,000 5-star reviews and counting", items: [{ name: "Jessica M.", role: "Verified Buyer", text: "I've been shopping with LUXE for over 2 years and every single purchase has exceeded my expectations. The leather tote is my everyday bag — it's gorgeous and incredibly well-made. Already ordered my second one as a gift.", rating: 5 }, { name: "David K.", role: "Verified Buyer", text: "The attention to detail is unreal. From the beautifully designed packaging to the quality of the products, everything feels premium. The ceramic pour-over set makes coffee that rivals my local specialty café.", rating: 5 }, { name: "Aisha R.", role: "Verified Buyer", text: "Finally, a brand that delivers on its promises. The linen bedding is absolutely divine — it gets softer with every wash, just like they said. Customer support was also incredibly helpful when I needed to exchange sizes.", rating: 5 }] } },
                { id: "newsletter-1", type: "newsletter", content: { title: "Join the LUXE Community", subtitle: "Be the first to know about new arrivals, exclusive offers, and styling tips. Plus, get 15% off your first order.", placeholder: "Enter your email address", buttonText: "Get 15% Off", incentive: "Get 15% off your first order" } },
                { id: "faq-1", type: "faq", content: { title: "Frequently Asked Questions", subtitle: "Everything you need to know about shopping with us", items: [{ question: "What is your shipping policy?", answer: "We offer free standard shipping on all orders over $75. Standard shipping typically takes 3-5 business days. Express shipping ($12.99) delivers in 1-2 business days. All orders include tracking and signature confirmation for orders over $200." }, { question: "What is your return policy?", answer: "We offer a 30-day hassle-free return policy. If you're not completely satisfied with your purchase, you can return it for a full refund or exchange. Items must be in their original condition with tags attached. We provide free return shipping labels." }, { question: "How do I earn and redeem loyalty points?", answer: "You earn 2 points for every $1 spent. Points can be redeemed starting at 200 points ($5 off). You also earn bonus points for writing reviews (50 points), referring friends (500 points), and on your birthday (100 points). Points never expire." }, { question: "Do you offer gift wrapping?", answer: "Every LUXE order comes beautifully packaged at no extra cost. For an elevated gifting experience, we offer a premium gift box upgrade ($8.99) that includes a handwritten note card and a signature LUXE ribbon wrap." }, { question: "Are your products sustainably made?", answer: "Yes! Sustainability is core to our mission. We work exclusively with certified manufacturers who meet strict environmental and ethical standards. Our packaging is 100% recycled and recyclable. We're also a certified B Corporation and 1% for the Planet member." }, { question: "How can I track my order?", answer: "Once your order ships, you'll receive an email with a tracking link. You can also track your order by logging into your account and visiting the 'Orders' section. Our customer support team is available 24/7 if you have any questions about your delivery." }] } },
                { id: "about-1", type: "about", content: { title: "Our Story", description: "LUXE was born from a simple belief: everyday essentials should be extraordinary. Founded in 2021 by a team of product designers and makers, we set out to curate a collection of beautifully crafted goods that bring joy to the everyday moments — from your morning coffee ritual to the way you unwind at night. Every product in our store has been hand-selected, tested, and approved by our team. We partner with independent artisans, family-run workshops, and certified sustainable manufacturers from around the world.", image: "", stats: [{ value: "50K+", label: "Happy Customers" }, { value: "200+", label: "Products" }, { value: "4.9★", label: "Average Rating" }, { value: "30-Day", label: "Free Returns" }] } },
                { id: "contact-1", type: "contact", content: { title: "Get in Touch", subtitle: "We're here to help with orders, product questions, or anything else", email: "hello@luxe-store.com", phone: "+1 (888) 555-LUXE", address: "234 Commerce Street, Suite 200, Brooklyn, NY 11201", formFields: [{ label: "Full Name", type: "text", placeholder: "Your name" }, { label: "Email Address", type: "email", placeholder: "you@example.com" }, { label: "Order Number (optional)", type: "text", placeholder: "#LUXE-00000" }, { label: "How can we help?", type: "textarea", placeholder: "Tell us about your question, concern, or feedback..." }] } },
                { id: "footer-1", type: "footer", content: { logo: "LUXE", description: "Curated essentials for modern living. Quality goods, sustainably made.", links: [{ title: "Shop", items: [{ label: "New Arrivals", href: "#" }, { label: "Best Sellers", href: "#" }, { label: "Collections", href: "#" }, { label: "Gift Cards", href: "#" }, { label: "Sale", href: "#" }] }, { title: "Help", items: [{ label: "Shipping & Returns", href: "#" }, { label: "FAQ", href: "#" }, { label: "Size Guide", href: "#" }, { label: "Track Order", href: "#" }, { label: "Contact Us", href: "#" }] }, { title: "Company", items: [{ label: "Our Story", href: "#" }, { label: "Sustainability", href: "#" }, { label: "Careers", href: "#" }, { label: "Press", href: "#" }, { label: "Affiliates", href: "#" }] }], social: [{ platform: "instagram", url: "#" }, { platform: "tiktok", url: "#" }, { platform: "pinterest", url: "#" }, { platform: "facebook", url: "#" }], copyright: "© 2024 LUXE. All rights reserved. Sustainably made with ♥" } }
            ]
        }
    },
    {
        id: "business-starter",
        name: "Modern Business",
        category: "business",
        description: "Premium SaaS-style business platform with analytics dashboard, team features, and conversion-optimized layout",
        content: {
            siteName: "Nexus Pro",
            category: "business",
            theme: { primaryColor: "#6366f1", secondaryColor: "#0ea5e9", accentColor: "#f43f5e", backgroundColor: "#ffffff", textColor: "#1a1a2e", fontFamily: "Inter" },
            sections: [
                { id: "nav-1", type: "navbar", content: { logo: "Nexus Pro", links: [{ label: "Features", href: "#features" }, { label: "Pricing", href: "#pricing" }, { label: "About", href: "#about" }, { label: "Testimonials", href: "#testimonials" }, { label: "Contact", href: "#contact" }], ctaText: "Start Free Trial", ctaLink: "#pricing" } },
                { id: "hero-1", type: "hero", content: { headline: "Scale Your Business 10x Faster with AI-Powered Automation", subheadline: "The all-in-one platform that helps 5,000+ companies automate workflows, close deals faster, and grow revenue — without adding headcount.", ctaText: "Start Free Trial — No Credit Card", ctaLink: "#pricing", backgroundImage: "", overlayOpacity: 0.5 } },
                { id: "feat-1", type: "features", content: { title: "Everything You Need to Dominate Your Market", subtitle: "Powerful tools built for modern teams that move fast", items: [{ icon: "🚀", title: "AI-Powered Analytics", description: "Get real-time insights with predictive analytics. Our AI engine processes millions of data points to surface actionable recommendations that drive growth." }, { icon: "🔒", title: "Enterprise Security", description: "SOC 2 Type II certified, GDPR compliant, with end-to-end encryption. Your data is protected by the same technology used by Fortune 500 companies." }, { icon: "⚡", title: "Lightning-Fast API", description: "99.99% uptime with response times under 50ms. Our globally distributed infrastructure ensures your apps run at peak performance worldwide." }, { icon: "🤖", title: "Smart Automation", description: "Eliminate repetitive tasks with intelligent workflows. Set up once and watch your team save 20+ hours per week on manual processes." }, { icon: "📊", title: "Custom Dashboards", description: "Build beautiful dashboards in minutes with drag-and-drop. Share real-time reports with stakeholders and make data-driven decisions faster." }, { icon: "🔗", title: "200+ Integrations", description: "Connect with every tool your team already uses — Slack, Salesforce, HubSpot, Zapier, and 200+ more. Zero coding required." }] } },
                { id: "pricing-1", type: "pricing", content: { title: "Simple, Transparent Pricing", subtitle: "No hidden fees. Cancel anytime. Start free.", plans: [{ name: "Starter", price: "$29", period: "/month", features: ["Up to 5 team members", "10,000 API calls/month", "Basic analytics dashboard", "Email support", "5 custom workflows"], ctaText: "Start Free Trial", highlighted: false }, { name: "Professional", price: "$79", period: "/month", features: ["Up to 25 team members", "100,000 API calls/month", "Advanced AI analytics", "Priority support (4h SLA)", "Unlimited workflows", "Custom integrations", "SSO & SAML"], ctaText: "Start Free Trial", highlighted: true }, { name: "Enterprise", price: "$199", period: "/month", features: ["Unlimited team members", "Unlimited API calls", "Full AI suite + custom models", "Dedicated account manager", "Custom SLA & uptime guarantee", "On-premise deployment option", "SOC 2 audit report access"], ctaText: "Contact Sales", highlighted: false }] } },
                { id: "about-1", type: "about", content: { title: "Trusted by Industry Leaders Worldwide", description: "Founded in 2019 by ex-Google engineers, Nexus Pro was born from a simple belief: every business deserves enterprise-grade tools without the enterprise price tag. Today, we power operations for companies across 40+ countries, processing over 2 billion events per month.", image: "", stats: [{ value: "5,000+", label: "Companies" }, { value: "99.99%", label: "Uptime" }, { value: "150M+", label: "Events/Day" }, { value: "4.9★", label: "Rating" }] } },
                { id: "testimonials-1", type: "testimonials", content: { title: "Loved by the Teams That Use Us", subtitle: "Don't just take our word for it", items: [{ name: "Sarah Chen", role: "VP of Engineering, TechFlow", text: "Nexus Pro cut our deployment time by 73%. What used to take 2 days now happens in hours. The AI analytics alone have paid for the subscription 10x over.", rating: 5 }, { name: "Marcus Williams", role: "CEO, GrowthStack", text: "We evaluated 12 platforms before choosing Nexus Pro. The combination of powerful automation, beautiful UI, and responsive support is unmatched in this space.", rating: 5 }, { name: "Elena Rodriguez", role: "Head of Operations, ScaleUp Inc", text: "The custom dashboards feature is a game-changer. My team went from spending 15 hours weekly on reports to getting real-time insights at a glance.", rating: 5 }] } },
                { id: "contact-1", type: "contact", content: { title: "Ready to Get Started?", subtitle: "Talk to our team and get a personalized demo", email: "hello@nexuspro.io", phone: "+1 (888) 456-7890", address: "100 Market Street, Suite 400, San Francisco, CA 94105", formFields: [{ label: "Full Name", type: "text", placeholder: "John Doe" }, { label: "Work Email", type: "email", placeholder: "john@company.com" }, { label: "Company Size", type: "text", placeholder: "e.g., 50-200 employees" }, { label: "How can we help?", type: "textarea", placeholder: "Tell us about your goals and challenges..." }] } },
                { id: "footer-1", type: "footer", content: { logo: "Nexus Pro", description: "AI-powered business automation for modern teams.", links: [{ title: "Product", items: [{ label: "Features", href: "#" }, { label: "Pricing", href: "#" }, { label: "API Docs", href: "#" }, { label: "Changelog", href: "#" }] }, { title: "Company", items: [{ label: "About", href: "#" }, { label: "Blog", href: "#" }, { label: "Careers", href: "#" }, { label: "Press Kit", href: "#" }] }], social: [{ platform: "twitter", url: "#" }, { platform: "linkedin", url: "#" }, { platform: "github", url: "#" }], copyright: "© 2024 Nexus Pro. All rights reserved." } }
            ]
        }
    },
    {
        id: "portfolio-creative",
        name: "Creative Portfolio",
        category: "portfolio",
        description: "Award-winning portfolio with case studies, services, testimonials, and premium dark-mode aesthetic",
        content: {
            siteName: "Aria Studio",
            category: "portfolio",
            theme: { primaryColor: "#ec4899", secondaryColor: "#8b5cf6", accentColor: "#f59e0b", backgroundColor: "#ffffff", textColor: "#1a1a2e", fontFamily: "DM Sans" },
            sections: [
                { id: "nav-1", type: "navbar", content: { logo: "✦ Aria Studio", links: [{ label: "Services", href: "#services" }, { label: "Work", href: "#work" }, { label: "About", href: "#about" }, { label: "Testimonials", href: "#testimonials" }, { label: "Contact", href: "#contact" }], ctaText: "Let's Talk", ctaLink: "#contact" } },
                { id: "hero-1", type: "hero", content: { headline: "I Craft Digital Experiences That Convert Visitors into Customers", subheadline: "Award-winning designer & full-stack developer with 10+ years helping startups and Fortune 500 brands build products people love.", ctaText: "View Case Studies", ctaLink: "#work", backgroundImage: "", overlayOpacity: 0.5 } },
                { id: "serv-1", type: "services", content: { title: "Services That Drive Results", subtitle: "End-to-end design and development tailored to your vision", items: [{ icon: "🎨", title: "Brand Identity & UI Design", description: "From logo to full design systems — cohesive visual identities that make brands unforgettable. I design with conversion psychology baked in.", price: "From $4,500" }, { icon: "💻", title: "Full-Stack Web Development", description: "Blazing-fast, SEO-optimized websites built with React, Next.js, and modern frameworks. Every pixel hand-crafted for performance.", price: "From $8,000" }, { icon: "📱", title: "Mobile App Design & Dev", description: "Native iOS/Android and cross-platform apps with beautiful UX. From concept to App Store, I handle the full journey.", price: "From $12,000" }, { icon: "📈", title: "Growth & Conversion Strategy", description: "Data-driven landing pages, A/B testing, and conversion funnels that routinely achieve 2-5x improvement.", price: "From $3,000" }] } },
                { id: "feat-1", type: "features", content: { title: "Why Clients Choose Me", subtitle: "More than just design — a strategic partner for your business", items: [{ icon: "🏆", title: "Award-Winning Work", description: "3x Awwwards Site of the Day, featured in Dribbble's Top 100, and recognized by CSS Design Awards annually." }, { icon: "⚡", title: "Lightning Turnaround", description: "Most projects delivered in 2-4 weeks. I respect your timeline because I know speed matters in competitive markets." }, { icon: "🤝", title: "Collaborative Process", description: "Weekly check-ins, shared Figma boards, and transparent communication. You're never in the dark about progress." }, { icon: "📊", title: "Results-Driven", description: "Average client sees 340% increase in engagement and 2.8x improvement in conversion rates within 90 days." }] } },
                { id: "about-1", type: "about", content: { title: "The Story Behind the Pixels", description: "I'm Aria — a self-taught designer turned full-stack developer who fell in love with the intersection of aesthetics and engineering. After 6 years at agencies (including IDEO and Pentagram), I went independent to give every client the premium attention they deserve. My work has generated over $50M in client revenue.", image: "", stats: [{ value: "200+", label: "Projects Shipped" }, { value: "$50M+", label: "Client Revenue" }, { value: "10+", label: "Years Experience" }, { value: "98%", label: "Client Retention" }] } },
                { id: "testimonials-1", type: "testimonials", content: { title: "What My Clients Say", subtitle: "Real results from real partnerships", items: [{ name: "David Park", role: "Founder & CEO, LaunchPad", text: "Aria redesigned our entire SaaS platform. Within 60 days, our trial-to-paid conversion jumped from 8% to 23%. She doesn't just design — she understands business.", rating: 5 }, { name: "Jessica Lee", role: "Marketing Director, Bloom & Co", text: "Working with Aria felt like having a co-founder who happens to be a world-class designer. She challenged our assumptions and delivered something 10x better.", rating: 5 }, { name: "Tom Nakamura", role: "CTO, DataVerse", text: "The code quality is as impressive as the design. Clean, well-documented, performant. Our developers actually enjoy working with her codebase.", rating: 5 }] } },
                { id: "pricing-1", type: "pricing", content: { title: "Engagement Models", subtitle: "Flexible options to fit your project and budget", plans: [{ name: "Project-Based", price: "$5K", period: "starting at", features: ["Dedicated project scope", "2-4 week delivery", "3 rounds of revisions", "Source files included", "30-day post-launch support"], ctaText: "Get a Quote", highlighted: false }, { name: "Monthly Retainer", price: "$4K", period: "/month", features: ["40 hours/month", "Ongoing design & dev support", "Priority scheduling", "Weekly strategy calls", "Unlimited revisions", "Slack/Discord access", "Cancel anytime"], ctaText: "Start Retainer", highlighted: true }, { name: "Full Partnership", price: "Custom", period: "pricing", features: ["Embedded team member", "Daily standups", "Full product ownership", "Growth strategy included", "Revenue share options", "Long-term commitment", "Custom SLA"], ctaText: "Let's Talk", highlighted: false }] } },
                { id: "contact-1", type: "contact", content: { title: "Let's Build Something Amazing", subtitle: "Every great project starts with a conversation", email: "hello@ariastudio.co", phone: "+1 (415) 555-0199", address: "Working remotely from San Francisco & Tokyo", formFields: [{ label: "Your Name", type: "text", placeholder: "Jane Smith" }, { label: "Email", type: "email", placeholder: "jane@company.com" }, { label: "Budget Range", type: "text", placeholder: "$5K-$10K, $10K-$25K, $25K+" }, { label: "Tell me about your project", type: "textarea", placeholder: "What are you building? What's your timeline?" }] } },
                { id: "footer-1", type: "footer", content: { logo: "✦ Aria Studio", description: "Crafting digital experiences that move the needle.", links: [{ title: "Quick Links", items: [{ label: "Services", href: "#" }, { label: "Case Studies", href: "#" }, { label: "Blog", href: "#" }, { label: "Resources", href: "#" }] }], social: [{ platform: "instagram", url: "#" }, { platform: "twitter", url: "#" }, { platform: "dribbble", url: "#" }, { platform: "linkedin", url: "#" }], copyright: "© 2024 Aria Studio. Designed with ♥ in SF." } }
            ]
        }
    },
    {
        id: "restaurant-elegant",
        name: "Fine Dining",
        category: "restaurant",
        description: "Michelin-inspired restaurant with seasonal menus, sommelier selections, and reservation system",
        content: {
            siteName: "Aurelian",
            category: "restaurant",
            theme: { primaryColor: "#92400e", secondaryColor: "#78350f", accentColor: "#b91c1c", backgroundColor: "#fffbf5", textColor: "#1c1917", fontFamily: "Playfair Display" },
            sections: [
                { id: "nav-1", type: "navbar", content: { logo: "✦ Aurelian", links: [{ label: "Menu", href: "#menu" }, { label: "Experience", href: "#features" }, { label: "Our Story", href: "#about" }, { label: "Reviews", href: "#testimonials" }, { label: "Reserve", href: "#contact" }], ctaText: "Reserve a Table", ctaLink: "#contact" } },
                { id: "hero-1", type: "hero", content: { headline: "Where Every Course Tells a Story", subheadline: "Two Michelin stars. Seasonal ingredients from our farm. An unforgettable evening crafted by Chef Laurent Dubois and his team of culinary artists.", ctaText: "Reserve Your Experience", ctaLink: "#contact", backgroundImage: "", overlayOpacity: 0.5 } },
                { id: "feat-1", type: "features", content: { title: "The Aurelian Experience", subtitle: "More than dinner — an evening of culinary artistry", items: [{ icon: "🌿", title: "Farm-to-Table Philosophy", description: "95% of our ingredients come from our 12-acre organic farm in Napa Valley. What we can't grow, we source from local artisan producers." }, { icon: "🍷", title: "Sommelier-Curated Pairings", description: "Our master sommelier has assembled a 3,000-bottle cellar spanning 15 countries. Every course has a perfect pairing." }, { icon: "👨‍🍳", title: "Open Kitchen Theater", description: "Watch Chef Laurent and his brigade craft each dish in our stunning open kitchen. Every plate is a performance of precision." }, { icon: "🎵", title: "Live Jazz Evenings", description: "Thursday through Saturday, enjoy world-class jazz trios performing in our intimate lounge." }] } },
                { id: "menu-1", type: "menu-card", content: { title: "Seasonal Tasting Menu", subtitle: "12-course journey through autumn's finest — $185 per person", categories: [{ name: "Amuse-Bouche & Starters", items: [{ name: "Kumamoto Oyster Trio", description: "Champagne mignonette, finger lime, yuzu kosho — three preparations celebrating Pacific perfection", price: "$24", image: "" }, { name: "Black Truffle Risotto", description: "Arborio rice, aged parmesan, winter black truffle shaved tableside with brown butter foam", price: "$32", image: "" }, { name: "Hamachi Crudo", description: "Yellowtail sashimi, blood orange, shiso, crispy shallots, aged dashi vinaigrette", price: "$28", image: "" }] }, { name: "Main Courses", items: [{ name: "A5 Wagyu Tenderloin", description: "Japanese A5 grade, 6oz, roasted bone marrow butter, seasonal root vegetables, red wine jus", price: "$95", image: "" }, { name: "Pan-Roasted Dover Sole", description: "Whole fish, brown butter, capers, lemon, hand-harvested sea beans from Mendocino Coast", price: "$68", image: "" }, { name: "Heritage Duck Breast", description: "Sonoma Liberty duck, cherry gastrique, duck fat confit potatoes, wilted bitter greens", price: "$52", image: "" }] }, { name: "Desserts", items: [{ name: "Chocolate Soufflé", description: "Valrhona dark chocolate, crème anglaise, candied Meyer lemon — please allow 20 minutes", price: "$18", image: "" }, { name: "Fromage Selection", description: "5 artisan cheeses, honeycomb, seasonal fruit compote, walnut bread from our wood-fired oven", price: "$22", image: "" }] }] } },
                { id: "about-1", type: "about", content: { title: "A Legacy of Culinary Excellence", description: "Chef Laurent Dubois trained under Alain Ducasse in Paris before opening Aurelian in 2015. Within two years, the restaurant earned its first Michelin star. The second followed in 2019. Today, Aurelian is recognized as one of America's finest dining destinations.", image: "", stats: [{ value: "⭐⭐", label: "Michelin Stars" }, { value: "#12", label: "World's Best" }, { value: "9", label: "Years Running" }, { value: "50K+", label: "Guests Served" }] } },
                { id: "testimonials-1", type: "testimonials", content: { title: "From Our Guests", subtitle: "Every evening at Aurelian is a memory in the making", items: [{ name: "Robert & Emily Harris", role: "Anniversary Dinner", text: "Our 25th anniversary dinner was transcendent. The tasting menu was flawless, the service impeccable, and the sommelier pairing was a revelation.", rating: 5 }, { name: "Amanda Thornton", role: "Food Critic, The Chronicle", text: "Aurelian isn't just serving food — it's telling stories on a plate. Each course arrives with intention, from the playful amuse-bouche to the final soufflé.", rating: 5 }, { name: "James Hiro", role: "Regular Guest", text: "I've been coming monthly for three years. The seasonal menu keeps it endlessly exciting, and the staff remembers every detail about my preferences.", rating: 5 }] } },
                { id: "contact-1", type: "contact", content: { title: "Reserve Your Table", subtitle: "We recommend booking 2-3 weeks in advance for weekend dining", email: "reservations@aurelian.com", phone: "+1 (415) 555-8765", address: "1847 Vine Street, Napa Valley, CA 94559", formFields: [{ label: "Guest Name", type: "text", placeholder: "Your name" }, { label: "Email", type: "email", placeholder: "your@email.com" }, { label: "Preferred Date & Time", type: "text", placeholder: "e.g., Saturday 7:30 PM" }, { label: "Special Requests", type: "textarea", placeholder: "Dietary restrictions, celebrations, seating preferences..." }] } },
                { id: "footer-1", type: "footer", content: { logo: "✦ Aurelian", description: "Two Michelin Stars. Farm-to-Table. Napa Valley.", links: [{ title: "Visit Us", items: [{ label: "Tue-Thu: 6pm-10pm", href: "#" }, { label: "Fri-Sat: 5:30pm-11pm", href: "#" }, { label: "Sun: Brunch 11am-3pm", href: "#" }, { label: "Monday: Closed", href: "#" }] }, { title: "Explore", items: [{ label: "Private Events", href: "#" }, { label: "Gift Cards", href: "#" }, { label: "Wine Club", href: "#" }, { label: "Chef's Table", href: "#" }] }], social: [{ platform: "instagram", url: "#" }, { platform: "facebook", url: "#" }], copyright: "© 2024 Aurelian Restaurant. All rights reserved." } }
            ]
        }
    },
    {
        id: "local-service",
        name: "Home Services",
        category: "local-service",
        description: "Professional service company with booking system, service tiers, customer reviews, and trust signals",
        content: {
            siteName: "EliteCraft",
            category: "local-service",
            theme: { primaryColor: "#0284c7", secondaryColor: "#0369a1", accentColor: "#f97316", backgroundColor: "#ffffff", textColor: "#1e293b", fontFamily: "Space Grotesk" },
            sections: [
                { id: "nav-1", type: "navbar", content: { logo: "⚡ EliteCraft", links: [{ label: "Services", href: "#services" }, { label: "Why Us", href: "#features" }, { label: "Pricing", href: "#pricing" }, { label: "Reviews", href: "#testimonials" }, { label: "Book Now", href: "#contact" }], ctaText: "Get Free Quote", ctaLink: "#contact" } },
                { id: "hero-1", type: "hero", content: { headline: "Expert Home Services — Done Right the First Time", subheadline: "Licensed, insured, and 5-star rated. EliteCraft handles everything from emergency plumbing to full kitchen renovations — with same-day service available.", ctaText: "Get Your Free Quote Today", ctaLink: "#contact", backgroundImage: "", overlayOpacity: 0.5 } },
                { id: "serv-1", type: "services", content: { title: "Professional Services for Every Home Need", subtitle: "Fully licensed, bonded & insured — guaranteed satisfaction", items: [{ icon: "🔧", title: "Plumbing & Water Systems", description: "Emergency leaks, drain clearing, water heater installation, pipe replacement, bathroom remodels, and sewer line repair. Available 24/7.", price: "From $89" }, { icon: "⚡", title: "Electrical Services", description: "Panel upgrades, outlet installation, lighting design, EV charger setup, smart home wiring, and full rewiring for older homes.", price: "From $110" }, { icon: "❄️", title: "HVAC & Climate Control", description: "AC installation & repair, furnace maintenance, duct cleaning, smart thermostat setup, and energy efficiency audits.", price: "From $95" }, { icon: "🏠", title: "General Contracting", description: "Kitchen & bath renovations, flooring, drywall repair, painting, deck building, and complete home remodeling projects.", price: "From $150" }, { icon: "🛡️", title: "Home Inspections", description: "Pre-purchase inspections, annual maintenance checks, radon testing, mold assessment, and detailed digital reports.", price: "From $250" }] } },
                { id: "feat-1", type: "features", content: { title: "The EliteCraft Difference", subtitle: "Why 8,000+ homeowners trust us with their homes", items: [{ icon: "✅", title: "Same-Day Service", description: "Emergency? We're there within 2 hours. Standard appointments available same-day. No more waiting around." }, { icon: "💰", title: "Upfront Pricing", description: "No surprises, no hidden fees. You'll get a detailed quote before any work begins — and we guarantee it." }, { icon: "🛡️", title: "Lifetime Guarantee", description: "Every job comes with our industry-leading lifetime workmanship guarantee. If it fails, we fix it free. Period." }, { icon: "📱", title: "Real-Time Tracking", description: "Track your technician's arrival via our app. Get photo updates during the job and a completion report when done." }] } },
                { id: "pricing-1", type: "pricing", content: { title: "Service Plans", subtitle: "Save up to 30% with a maintenance plan", plans: [{ name: "Basic Care", price: "$29", period: "/month", features: ["Annual HVAC tune-up", "Priority scheduling", "10% off all repairs", "Phone support", "Annual plumbing check"], ctaText: "Get Started", highlighted: false }, { name: "Home Shield", price: "$59", period: "/month", features: ["Bi-annual HVAC service", "Same-day priority", "20% off all repairs", "Annual electrical inspection", "Plumbing maintenance", "Water heater flush", "24/7 emergency line"], ctaText: "Best Value", highlighted: true }, { name: "Total Protection", price: "$99", period: "/month", features: ["Quarterly full-home inspection", "VIP 1-hour response time", "30% off all repairs", "All systems covered", "Drain camera inspection", "Dedicated account manager", "Annual appliance check"], ctaText: "Go Premium", highlighted: false }] } },
                { id: "about-1", type: "about", content: { title: "Serving Our Community Since 2012", description: "EliteCraft was founded by master tradesman Mike Reeves with one mission: bring honest, high-quality home services to families tired of unreliable contractors. Today, our team of 45+ certified technicians serves 15,000+ homes annually.", image: "", stats: [{ value: "8,200+", label: "5-Star Reviews" }, { value: "15K+", label: "Homes Served" }, { value: "45+", label: "Expert Techs" }, { value: "Same Day", label: "Service Available" }] } },
                { id: "testimonials-1", type: "testimonials", content: { title: "Trusted by Your Neighbors", subtitle: "8,200+ five-star reviews and counting", items: [{ name: "Karen Mitchell", role: "Homeowner, Oak Park", text: "EliteCraft replaced our entire HVAC system in one day. The crew was professional, clean, and the upfront pricing was exactly what we paid. No surprises.", rating: 5 }, { name: "Robert Chang", role: "Homeowner, Riverside", text: "Had an emergency pipe burst at 2 AM. Called EliteCraft and they had someone at my door within 90 minutes. Saved us from thousands in water damage.", rating: 5 }, { name: "Lisa & Tom Martinez", role: "Homeowners, Brookfield", text: "We've used every service they offer — plumbing, electrical, HVAC, and a full bathroom renovation. Consistent quality every time.", rating: 5 }] } },
                { id: "contact-1", type: "contact", content: { title: "Get Your Free Quote in Minutes", subtitle: "No obligation. No pressure. Just honest answers.", email: "service@elitecraft.com", phone: "+1 (888) 555-CRAFT", address: "Serving the entire Greater Metro Area — 50 mile radius", formFields: [{ label: "Your Name", type: "text", placeholder: "Full name" }, { label: "Phone Number", type: "text", placeholder: "(555) 123-4567" }, { label: "Service Needed", type: "text", placeholder: "e.g., Plumbing, Electrical, HVAC" }, { label: "Describe the Issue", type: "textarea", placeholder: "Tell us what's going on and when you need it fixed..." }] } },
                { id: "footer-1", type: "footer", content: { logo: "⚡ EliteCraft", description: "Licensed. Insured. Guaranteed. Your home deserves the best.", links: [{ title: "Services", items: [{ label: "Plumbing", href: "#" }, { label: "Electrical", href: "#" }, { label: "HVAC", href: "#" }, { label: "Renovations", href: "#" }] }, { title: "Company", items: [{ label: "About Us", href: "#" }, { label: "Careers", href: "#" }, { label: "Service Areas", href: "#" }, { label: "Blog", href: "#" }] }], social: [{ platform: "facebook", url: "#" }, { platform: "instagram", url: "#" }, { platform: "google", url: "#" }], copyright: "© 2024 EliteCraft Home Services. License #HIC-123456." } }
            ]
        }
    },
    {
        id: "event-landing",
        name: "Event Landing",
        category: "event",
        description: "Premium tech conference with speaker lineup, multi-day schedule, VIP packages, and early-bird pricing",
        content: {
            siteName: "Horizon Summit",
            category: "event",
            theme: { primaryColor: "#7c3aed", secondaryColor: "#6366f1", accentColor: "#ec4899", backgroundColor: "#ffffff", textColor: "#1a1a2e", fontFamily: "Outfit" },
            sections: [
                { id: "nav-1", type: "navbar", content: { logo: "◆ Horizon Summit 2025", links: [{ label: "Speakers", href: "#features" }, { label: "Agenda", href: "#services" }, { label: "Tickets", href: "#pricing" }, { label: "Testimonials", href: "#testimonials" }, { label: "Location", href: "#contact" }], ctaText: "Get Tickets →", ctaLink: "#pricing" } },
                { id: "hero-1", type: "hero", content: { headline: "Where the Future of Technology Gets Built", subheadline: "Join 5,000+ founders, engineers, designers, and investors for 3 days of groundbreaking talks, hands-on workshops, and unmatched networking. March 18-20, 2025 • San Francisco.", ctaText: "Get Early Bird Tickets — Save 40%", ctaLink: "#pricing", backgroundImage: "", overlayOpacity: 0.5 } },
                { id: "feat-1", type: "features", content: { title: "World-Class Speakers & Thought Leaders", subtitle: "Learn from the people shaping tomorrow's technology", items: [{ icon: "🎤", title: "80+ Expert Speakers", description: "CTOs, founders, and researchers from Google, OpenAI, Stripe, Vercel, and 50+ leading companies sharing insights." }, { icon: "🛠️", title: "40+ Hands-On Workshops", description: "Deep-dive sessions in AI/ML, system design, product strategy, and emerging tech. Limited to 30 seats each." }, { icon: "🤝", title: "VIP Networking Lounges", description: "Curated 1-on-1 meetings with investors, co-founder matching sessions, and exclusive after-parties." }, { icon: "🏆", title: "Startup Pitch Competition", description: "$500K in prizes and guaranteed meetings with top-tier VCs. 20 startups selected from 2,000+ applications." }, { icon: "🌐", title: "Live Product Expo", description: "Demo your product to 5,000 attendees, 200+ investors, and 50+ media outlets. The ultimate launch platform." }, { icon: "🎬", title: "Lifetime Access to Recordings", description: "All keynotes and sessions professionally recorded in 4K. Every ticket includes lifetime access." }] } },
                { id: "serv-1", type: "services", content: { title: "Three Days of Groundbreaking Content", subtitle: "Your complete conference agenda", items: [{ icon: "📅", title: "Day 1 — AI & The Future", description: "Keynotes on generative AI, autonomous systems, and ethics. Featuring talks from OpenAI and DeepMind leadership.", price: "March 18" }, { icon: "📅", title: "Day 2 — Building at Scale", description: "System architecture, DevOps, platform engineering, and scaling from 0 to millions. Workshop-heavy day.", price: "March 19" }, { icon: "📅", title: "Day 3 — Product & Growth", description: "Product-led growth, design systems, user research, and the startup pitch competition finals.", price: "March 20" }] } },
                { id: "pricing-1", type: "pricing", content: { title: "Choose Your Experience", subtitle: "Early bird pricing ends February 1 — save up to 40%", plans: [{ name: "General Pass", price: "$399", period: "early bird", features: ["All keynotes & main stage", "Product expo access", "Networking lounges", "Lunch & refreshments", "Recording access (1 year)", "Conference swag bag"], ctaText: "Get General Pass", highlighted: false }, { name: "Pro Pass", price: "$799", period: "early bird", features: ["Everything in General +", "All 40+ workshops", "Priority front-row seating", "Speaker meet & greet", "Lifetime recordings", "Private Slack community", "Certificate of completion"], ctaText: "Get Pro Pass", highlighted: true }, { name: "VIP Experience", price: "$1,499", period: "early bird", features: ["Everything in Pro +", "VIP lounge & concierge", "Speaker dinner (exclusive)", "1-on-1 investor meetings", "Airport shuttle service", "Hotel (2 nights included)", "Exclusive after-party"], ctaText: "Go VIP", highlighted: false }] } },
                { id: "about-1", type: "about", content: { title: "By the Numbers", description: "Horizon Summit has grown from a 200-person meetup to one of the world's premier technology conferences. What started in 2019 now fills the Moscone Center and attracts attendees from 60+ countries. Our alumni include founders who've raised over $2B collectively.", image: "", stats: [{ value: "5,000+", label: "Attendees" }, { value: "80+", label: "Speakers" }, { value: "60+", label: "Countries" }, { value: "$2B+", label: "Alumni Raised" }] } },
                { id: "testimonials-1", type: "testimonials", content: { title: "What Past Attendees Say", subtitle: "96% say they'd attend again", items: [{ name: "Priya Sharma", role: "Founder & CEO, NexGen AI", text: "Horizon Summit is where I met my co-founder, my lead investor, and three of my first customers. This conference literally built my company.", rating: 5 }, { name: "Alex Rivera", role: "Staff Engineer, Stripe", text: "The technical depth here is unmatched. I attended the system design workshop and immediately applied patterns that reduced our latency by 40%.", rating: 5 }, { name: "Sophie Chen", role: "VP Product, Figma", text: "Most conferences feel like glorified webinars. Horizon Summit feels like a community. The hallway conversations alone are worth the trip.", rating: 5 }] } },
                { id: "contact-1", type: "contact", content: { title: "Join Us in San Francisco", subtitle: "Moscone Center • March 18-20, 2025", email: "info@horizonsummit.tech", phone: "+1 (888) 555-TECH", address: "Moscone Center, 747 Howard St, San Francisco, CA 94103", formFields: [{ label: "Full Name", type: "text", placeholder: "Your name" }, { label: "Email", type: "email", placeholder: "you@company.com" }, { label: "Company & Role", type: "text", placeholder: "e.g., CTO at Startup Inc" }, { label: "Questions or Group Booking", type: "textarea", placeholder: "Group discounts (10+), sponsorship, or speaking?" }] } },
                { id: "footer-1", type: "footer", content: { logo: "◆ Horizon Summit 2025", description: "Where the future of technology gets built. March 18-20, San Francisco.", links: [{ title: "Event", items: [{ label: "Schedule", href: "#" }, { label: "Speakers", href: "#" }, { label: "Sponsors", href: "#" }, { label: "Code of Conduct", href: "#" }] }, { title: "Attend", items: [{ label: "Tickets", href: "#" }, { label: "Travel & Hotels", href: "#" }, { label: "Visa Letters", href: "#" }, { label: "FAQs", href: "#" }] }], social: [{ platform: "twitter", url: "#" }, { platform: "linkedin", url: "#" }, { platform: "youtube", url: "#" }], copyright: "© 2024 Horizon Summit. Organized by TechEvents Inc." } }
            ]
        }
    },
    {
        id: "basic-store",
        name: "Product Showcase",
        category: "basic-store",
        description: "Premium D2C e-commerce brand with curated collections, customer reviews, loyalty program, and modern aesthetic",
        content: {
            siteName: "VERO",
            category: "basic-store",
            theme: { primaryColor: "#059669", secondaryColor: "#0d9488", accentColor: "#f43f5e", backgroundColor: "#ffffff", textColor: "#1a1a2e", fontFamily: "Sora" },
            sections: [
                { id: "nav-1", type: "navbar", content: { logo: "VERO", links: [{ label: "Collection", href: "#products" }, { label: "Why VERO", href: "#features" }, { label: "Reviews", href: "#testimonials" }, { label: "Our Story", href: "#about" }, { label: "Support", href: "#contact" }], ctaText: "Shop Now", ctaLink: "#products" } },
                { id: "hero-1", type: "hero", content: { headline: "Minimalism Meets Craftsmanship", subheadline: "Thoughtfully designed everyday essentials made from sustainable materials. Free shipping on orders over $75. 30-day hassle-free returns.", ctaText: "Shop the Collection", ctaLink: "#products", backgroundImage: "", overlayOpacity: 0.5 } },
                { id: "prod-1", type: "product-grid", content: { title: "The Essentials Collection", subtitle: "Handpicked pieces designed to last a lifetime", products: [{ name: "Heritage Leather Messenger", price: "$189", image: "", description: "Full-grain Italian leather, brass hardware, padded laptop sleeve. Ages beautifully.", badge: "Bestseller" }, { name: "Titanium Field Watch", price: "$295", image: "", description: "Swiss Ronda movement, sapphire crystal, grade 5 titanium. Water resistant to 200m.", badge: "New Arrival" }, { name: "Merino Wool Crew", price: "$85", image: "", description: "17.5 micron New Zealand merino. Temperature regulating, antimicrobial, machine washable.", badge: "Editor's Pick" }, { name: "Canvas Weekender", price: "$165", image: "", description: "Waxed canvas body, vegetable-tanned leather handles, shoe compartment.", badge: "" }, { name: "Ceramic Pour Over Set", price: "$68", image: "", description: "Hand-thrown stoneware, stainless steel filter. Makes 1-3 cups of perfect coffee.", badge: "Limited" }, { name: "Bamboo Desk Organizer", price: "$52", image: "", description: "Sustainably harvested moso bamboo. 5 compartments, cable management groove.", badge: "Sale" }] } },
                { id: "feat-1", type: "features", content: { title: "The VERO Promise", subtitle: "Every product tells a story of quality and conscience", items: [{ icon: "🌱", title: "Sustainably Made", description: "Every material is ethically sourced. We partner with certified B-Corp factories and offset 200% of our carbon footprint." }, { icon: "♻️", title: "Lifetime Warranty", description: "If any VERO product fails under normal use — ever — we'll repair or replace it free. No questions, no receipt needed." }, { icon: "🚚", title: "Free Carbon-Neutral Shipping", description: "Orders over $75 ship free. Every package is carbon-neutral in compostable packaging within 3-5 business days." }, { icon: "💝", title: "30-Day Love-It Guarantee", description: "Not sure? Try it for 30 days risk-free. Full refund, no restocking fee. We'll even cover return shipping." }] } },
                { id: "testimonials-1", type: "testimonials", content: { title: "What Our Community Says", subtitle: "12,000+ five-star reviews from real customers", items: [{ name: "Daniela Costa", role: "Verified Buyer", text: "The Heritage Messenger is the best bag I've ever owned. After 2 years of daily use, the leather has a gorgeous patina. It looks better now than day one.", rating: 5 }, { name: "Michael Okafor", role: "Verified Buyer", text: "I replaced every watch in my collection with the Titanium Field Watch. Lighter than my Apple Watch, looks stunning with any outfit. Perfection.", rating: 5 }, { name: "Emma Walsh", role: "Verified Buyer", text: "I gifted the Merino Crew to my partner who is extremely particular about fabrics. He ordered three more the next day. The quality is extraordinary.", rating: 5 }] } },
                { id: "about-1", type: "about", content: { title: "Objects Worth Keeping", description: "VERO was born in 2020 from a simple frustration: why does everything feel disposable? We set out to create a brand built on permanence — products made so well, you only need to buy them once. Designed in Portland, crafted by artisan partners, backed by our lifetime warranty.", image: "", stats: [{ value: "85K+", label: "Happy Customers" }, { value: "12K+", label: "5-Star Reviews" }, { value: "0.3%", label: "Return Rate" }, { value: "♻️", label: "B-Corp Certified" }] } },
                { id: "contact-1", type: "contact", content: { title: "We're Here to Help", subtitle: "Questions about sizing, materials, or your order? Our team responds within 2 hours.", email: "hello@vero.co", phone: "+1 (888) 555-VERO", address: "VERO HQ, 1234 Burnside St, Portland, OR 97214", formFields: [{ label: "Your Name", type: "text", placeholder: "Full name" }, { label: "Email", type: "email", placeholder: "your@email.com" }, { label: "Order Number (if applicable)", type: "text", placeholder: "#VERO-12345" }, { label: "How can we help?", type: "textarea", placeholder: "Sizing question, order issue, product recommendation..." }] } },
                { id: "footer-1", type: "footer", content: { logo: "VERO", description: "Thoughtfully designed. Built to last. Always sustainable.", links: [{ title: "Shop", items: [{ label: "All Products", href: "#" }, { label: "New Arrivals", href: "#" }, { label: "Bestsellers", href: "#" }, { label: "Gift Cards", href: "#" }] }, { title: "Support", items: [{ label: "Shipping & Returns", href: "#" }, { label: "Size Guide", href: "#" }, { label: "Warranty Claims", href: "#" }, { label: "Track Order", href: "#" }] }], social: [{ platform: "instagram", url: "#" }, { platform: "pinterest", url: "#" }, { platform: "tiktok", url: "#" }], copyright: "© 2024 VERO. Designed in Portland. Made responsibly." } }
            ]
        }
    }
];
